# Generated by Django 3.1.6 on 2021-02-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='english',
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
