# Generated by Django 3.1.6 on 2021-03-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210322_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
